### ISSUE TITLE
No such file or directory: src/backend/alacritty.rs:122:51

### ISSUE THREAD

**Issue by linrongbin16** [beeender/glrnvim#64]
1. M1 macbook, macOS Ventura 13.3
2. rustc 1.68.2 (9eb3afe9e 2023-03-27)
3. nvim version (latest development build):
```
NVIM v0.10.0-dev-36+g7ffe45017
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -I/Users/runner/work/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/local/include -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include -I/Users/runner/work/neovim/neovim/build/cmake.config -I/Users/runner/work/neovim/neovim/src -I/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Users/runner/work/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

4. backtrace:
```
$ RUST_BACKTRACE=full ./glrnvim
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/backend/alacritty.rs:122:51
stack backtrace:
   0:        0x10451ae04 - std::backtrace_rs::backtrace::libunwind::trace::h7e290481d10ef323
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10451ae04 - std::backtrace_rs::backtrace::trace_unsynchronized::h2aa61f03a3f6f25d
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10451ae04 - std::sys_common::backtrace::_print_fmt::hb1e5156405f26352
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x10451ae04 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3c406a4521928e59
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x104535144 - core::fmt::write::hc60df9bae744c40c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/fmt/mod.rs:1213:17
   5:        0x104518668 - std::io::Write::write_fmt::h1c4129dfc94f7c33
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/io/mod.rs:1682:15
   6:        0x10451ac18 - std::sys_common::backtrace::_print::h551adb153dee3888
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x10451ac18 - std::sys_common::backtrace::print::h34db077f1fa49c76
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x10451c2f8 - std::panicking::default_hook::{{closure}}::hff4fe3239c020cef
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:267:22
   9:        0x10451c050 - std::panicking::default_hook::hd2988fbcc86fdc46
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:286:9
  10:        0x10451c91c - std::panicking::rust_panic_with_hook::h01730ad11d62092c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:688:13
  11:        0x10451c73c - std::panicking::begin_panic_handler::{{closure}}::h30f454e305d4a708
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:579:13
  12:        0x10451b26c - std::sys_common::backtrace::__rust_end_short_backtrace::hb7ff1894d55794a1
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x10451c498 - rust_begin_unwind
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
  14:        0x104543320 - core::panicking::panic_fmt::hf1070b3fc33229fa
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
  15:        0x104543658 - core::result::unwrap_failed::h334387d5f1f555c1
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
  16:        0x1042e80f0 - core::result::Result<T,E>::unwrap::h09054a6847a0ae6e
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1112:23
  17:        0x104313068 - glrnvim::backend::alacritty::Alacritty::load_alacritty_conf::h9c390b23649c2370
                               at /Users/rlin/.glrnvim/src/backend/alacritty.rs:122:28
  18:        0x10430d18c - glrnvim::backend::alacritty::Alacritty::create_base_conf::{{closure}}::hb724ffb99f64925b
                               at /Users/rlin/.glrnvim/src/backend/alacritty.rs:40:17
  19:        0x10430d6f0 - core::option::Option<T>::map_or_else::hf006ecc03f68b0a5
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:1063:24
  20:        0x1043123ec - glrnvim::backend::alacritty::Alacritty::create_base_conf::h201a539e718b4c75
                               at /Users/rlin/.glrnvim/src/backend/alacritty.rs:33:9
  21:        0x104313220 - <glrnvim::backend::alacritty::Alacritty as glrnvim::backend::Functions>::create_command::hf808ca6fadb1591c
                               at /Users/rlin/.glrnvim/src/backend/alacritty.rs:136:29
  22:        0x104300c60 - glrnvim::main::h1c53cebe6e84c75b
                               at /Users/rlin/.glrnvim/src/main.rs:155:23
  23:        0x1042df0f0 - core::ops::function::FnOnce::call_once::hf53d4076724ff2f1
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
  24:        0x1043037a8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h507dae9cae0caf0b
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:121:18
  25:        0x1043119e0 - std::rt::lang_start::{{closure}}::ha479ab2442074e60
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:166:18
  26:        0x104514088 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfcba2619400775c8
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:287:13
  27:        0x104514088 - std::panicking::try::do_call::h3dbcab59a51ccd10
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  28:        0x104514088 - std::panicking::try::h4080a58a21c0db47
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  29:        0x104514088 - std::panic::catch_unwind::h51bc66584898e527
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  30:        0x104514088 - std::rt::lang_start_internal::{{closure}}::h8648c3428199657a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:48
  31:        0x104514088 - std::panicking::try::do_call::h5ef523fc3ef8d604
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  32:        0x104514088 - std::panicking::try::h8124f0d5fb60af33
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  33:        0x104514088 - std::panic::catch_unwind::h0d6a1ca206241be0
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  34:        0x104514088 - std::rt::lang_start_internal::h24d09c16ec322e75
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:20
  35:        0x1043119ac - std::rt::lang_start::h2865c7452de225d0
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:165:17
  36:        0x10430106c - _main
```

**Comment by linrongbin16** [comment]
https://github.com/beeender/glrnvim/blob/679dd9eb384320e5995dc567a0463b1971f9e237/src/backend/alacritty.rs#L122

I specified:
```
term_config_path: $HOME/.config/alacritty/alacritty.yml
```

It looks like the `$HOME` variable is not expand by `std::fs::File::open(p).unwrap();`, so the config file is not found.
